### ISSUE TITLE
Missing MAINTAINERS.md file

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/dashboards-desktop#26]
During an evaluation of our repos last week, I noticed this repository does not contain a MAINTAINERS.md file. Our https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md file provides an overview and outline to resolve this. 

I realize this is a template repo - if MAINTAINERS files are not standard practice on templates, go ahead and close this.

**Comment by Flyingliuhub** [comment]
Thanks @krisfreedain , we will add MAINTAINERS.md file for this repo.
