### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/dashboards-desktop#35]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by Flyingliuhub** [comment]
all set.

**Comment by dblock** [comment]
I don't believe the org "Admin" group has admin rights on this repo. Can you please add it?

**Comment by Flyingliuhub** [comment]
> I don't believe the org "Admin" group has admin rights on this repo. Can you please add it?
Thanks @dblock , I just added it.

**Comment by dblock** [comment]
- dashboards-anywhere-team-maintainers shouldn't exist, the folks that are maintainers should be explicitly added with Maintain access
- peterzhuamazon should not be Admin
- dashboards-anywhere-contributor should not exist, only maintainers should have r/w merge access

**Comment by seraphjiang** [comment]
@dblock 
dashboards-anywhere-contributor mapping to [CODEOWNERS](https://github.com/opensearch-project/dashboards-desktop/issues/CODEOWNERS) 

what permission should code owner has? could we use team to organize and manage?

**Comment by dblock** [comment]
We synced it.

![Screenshot 2023-03-02 at 6 43 23 PM](https://user-images.githubusercontent.com/542335/222590216-71be4419-2827-4ab8-9d08-f155306eafbf.png)
