### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/dashboards-desktop#37]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the Dashboards Desktop repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| Dashboards Desktop | <li>- [ ] </li> | <li>- [ ] </li> | <li>- [ ] </li> |  | https://github.com/opensearch-project/dashboards-desktop/issues/37 |

Judging from the state of the repository, I assume this is a new repo, but I wanted to check and see if there were any plans or anything else you would like to share.

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by seraphjiang** [comment]
This is new repo and not in actively development state.
